In [1]:
import numpy as np

In [2]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14]])

In [3]:
arr.T

array([[ 0, 5, 10],
 [ 1, 6, 11],
 [ 2, 7, 12],
 [ 3, 8, 13],
 [ 4, 9, 14]])

In [4]:
arc = np.random.randn(6,3)
arc

array([[ 1.59736944, 1.01328552, 0.88329359],
 [ 0.98974061, 0.4870414 , 2.47729779],
 [-1.21931667, -0.16221935, 0.81395333],
 [-0.08825887, 1.53712652, 2.16482435],
 [-0.50274043, 0.56288619, -0.09609365],
 [-1.80328797, -0.05113402, 0.2827634 ]])

In [5]:
print(type(arc))

<class 'numpy.ndarray'>


In [6]:
arc.T

array([[ 1.59736944, 0.98974061, -1.21931667, -0.08825887, -0.50274043,
 -1.80328797],
 [ 1.01328552, 0.4870414 , -0.16221935, 1.53712652, 0.56288619,
 -0.05113402],
 [ 0.88329359, 2.47729779, 0.81395333, 2.16482435, -0.09609365,
 0.2827634 ]])

In [7]:
np.dot(arr,arr.T)

array([[ 30, 80, 130],
 [ 80, 255, 430],
 [130, 430, 730]])

In [10]:
#tensor - tablica 3D
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [14]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [15]:
arr5D = np.arange(240).reshape((2,2,4,5,3))
arr5D

array([[[[[  0,   1,   2],
          [  3,   4,   5],
          [  6,   7,   8],
          [  9,  10,  11],
          [ 12,  13,  14]],

         [[ 15,  16,  17],
          [ 18,  19,  20],
          [ 21,  22,  23],
          [ 24,  25,  26],
          [ 27,  28,  29]],

         [[ 30,  31,  32],
          [ 33,  34,  35],
          [ 36,  37,  38],
          [ 39,  40,  41],
          [ 42,  43,  44]],

         [[ 45,  46,  47],
          [ 48,  49,  50],
          [ 51,  52,  53],
          [ 54,  55,  56],
          [ 57,  58,  59]]],


        [[[ 60,  61,  62],
          [ 63,  64,  65],
          [ 66,  67,  68],
          [ 69,  70,  71],
          [ 72,  73,  74]],

         [[ 75,  76,  77],
          [ 78,  79,  80],
          [ 81,  82,  83],
          [ 84,  85,  86],
          [ 87,  88,  89]],

         [[ 90,  91,  92],
          [ 93,  94,  95],
          [ 96,  97,  98],
          [ 99, 100, 101],
          [102, 103, 104]],

         [[105, 106, 107],
          [1

In [16]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
import math

In [20]:
# math.sqrt(arr)

np.sqrt(arr)

array([0. , 1. , 1.41421356, 1.73205081, 2. ,
 2.23606798, 2.44948974, 2.64575131, 2.82842712, 3. ])

In [21]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
 5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
 2.98095799e+03, 8.10308393e+03])

In [27]:
x = np.random.randn(8)
y = np.random.randn(8)
z = np.random.randn(8)

(x,y,z)

(array([ 1.98223715,  1.24345733, -0.11374877,  1.36059631,  0.96953   ,
         0.07288907, -0.52755454,  0.1138083 ]),
 array([-1.27715556, -1.25569347, -0.67627906,  0.19055554, -0.50388284,
        -0.73113161,  0.90871191, -1.09817034]),
 array([-1.02967435, -2.51769459, -0.54013454, -1.88536308,  0.48164262,
        -0.45174262, -0.41827778, -0.26388006]))

In [26]:
np.maximum(x,y,z)

array([2.18431506, 0.19648175, 1.44749669, 0.26733307, 0.21005551,
 0.67389907, 1.00009404, 0.13044434])

In [28]:
arr = np.random.randn(7)*6.5
arr

array([ 4.04522566, -0.58201984, 6.7524114 , -6.18647093,
 0.16914989, -2.15940386, -12.50466169])

In [29]:
remainder,whole_part = np.modf(arr)

In [30]:
remainder

array([ 0.04522566, -0.58201984, 0.7524114 , -0.18647093, 0.16914989,
 -0.15940386, -0.50466169])

In [31]:
whole_part

array([ 4., -0., 6., -6., 0., -2., -12.])