In [2]:
print("pierwsza komórka Jupyter")

pierwsza komórka Jupyter


# Podstawy pakietu NUMPY.<br>
Piszemy w **Datalore** (<span style="color:red; font-size:16pt; font-family:Impact;">Jupyter Notbook</span>)
<p>
<img src="numpylogo.png" width=300>
</p>
$\sqrt(x^2+y^2)$

In [3]:
import numpy as np

In [4]:
a = 'to jest bilbioteka numpy'
a

'to jest bilbioteka numpy'

In [5]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(22)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
 1., 1., 1., 1., 1.])

In [7]:
def split_sentence_into_words(sentence):
    words = sentence.split()
    return words

# Example usage
sample_sentence = "To jest przykładowe zdanie w języku polskim."
print(split_sentence_into_words(sample_sentence))

['To', 'jest', 'przykładowe', 'zdanie', 'w', 'języku', 'polskim.']


In [8]:
import requests

def fetch_data_from_website(url):
    try:
        response = requests.get(url)
        response.raise_for_status() # If the request was unsuccessful, an HTTPError will be raised
        return response.text # Returns the content in unicode
    except requests.exceptions.HTTPError as http_err:
        print(f'HTTP error occurred: {http_err}')  
    except Exception as err:
        print(f'Other error occurred: {err}') 

In [9]:
# Demonstrating the use of the fetch_data_from_website() function with Python's official website
website_url = "https://www.python.org/"
print(fetch_data_from_website(website_url))

<!doctype html>
<!--[if lt IE 7]>   <html class="no-js ie6 lt-ie7 lt-ie8 lt-ie9">   <![endif]-->
<!--[if IE 7]>      <html class="no-js ie7 lt-ie8 lt-ie9">          <![endif]-->
<!--[if IE 8]>      <html class="no-js ie8 lt-ie9">                 <![endif]-->
<!--[if gt IE 8]><!--><html class="no-js" lang="en" dir="ltr">  <!--<![endif]-->

<head>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-TF35YF9CVH"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-TF35YF9CVH');
    </script>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="prefetch" href="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js">
    <link rel="prefetch" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js">

    <meta name="application-name" content="Python.org">

In [10]:
u = np.arange(1,77,3)
u

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55, 58, 61, 64, 67, 70, 73, 76])

In [11]:
zlista = [3,89,7,45,24,5,72,11,34,25,78,73,7,29,41]
print(zlista)
print(type(zlista))

[3, 89, 7, 45, 24, 5, 72, 11, 34, 25, 78, 73, 7, 29, 41]
<class 'list'>


In [12]:
k = np.linspace(0,10,num=5)
k

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [13]:
print(type(k))

<class 'numpy.ndarray'>


In [15]:
mlista = np.array(zlista)
print(mlista)
print(type(mlista))

[ 3 89  7 45 24  5 72 11 34 25 78 73  7 29 41]
<class 'numpy.ndarray'>


In [16]:
krot = (3,255,247,673,24,8,32)
knum = np.array(krot)
print(knum)
print(type(knum))

[  3 255 247 673  24   8  32]
<class 'numpy.ndarray'>


In [17]:
zbior = {24,2,5,1,65,8,1,43,345,1}
znum = np.array(zbior)
print(znum)
print(type(znum))

{1, 2, 65, 5, 8, 43, 24, 345}
<class 'numpy.ndarray'>


In [18]:
knum.sort()
knum

array([ 3, 8, 24, 32, 247, 255, 673])

In [22]:
knum.shape

(7,)

In [21]:
znum.shape

()

In [24]:
zbior = {24,2,5,1,65,8,1,43,345,1}
zbior = list(zbior)
znum = np.array(zbior)
print(znum)
print(type(znum))
print(znum.shape)

[  1   2  65   5   8  43  24 345]
<class 'numpy.ndarray'>
(8,)


In [30]:
l1 = [2,4,6,9,34]
l2 = [9,6,76,3,13]
l3 = [45,6,7,1,14]

In [31]:
l = l1 + l2 + l3
l

[2, 4, 6, 9, 34, 9, 6, 76, 3, 13, 45, 6, 7, 1, 14]

In [32]:
a1 = np.array(l1)
a2 = np.array(l2)
a3 = np.array(l3)

In [33]:
a = a1 + a2 + a3

In [34]:
a

array([56, 16, 89, 13, 61])

In [35]:
az = np.concatenate((a1,a2,a3))

In [36]:
az

array([ 2, 4, 6, 9, 34, 9, 6, 76, 3, 13, 45, 6, 7, 1, 14])

In [40]:
extra = [54,452,67,358,93,25,9,67,8,9,24,11,14,63,3]

extra = extra + az
extra

array([ 56, 456, 73, 367, 127, 34, 15, 143, 11, 22, 69, 17, 21,
 64, 17])

In [41]:
#macierze

z1 = [[56,3],[11,67]]
print(type(z1))

<class 'list'>


In [43]:
z1[0][1]

3

In [45]:
aspec = np.array([[2,9],[18,4]])
aspec

array([[ 2, 9],
 [18, 4]])

In [47]:
aspec[1][0]

18

In [48]:
aspec[0,1]

9

In [51]:
x = np.array([[3,4],[3,13]])
y = np.array([[14,4],[23,2]])

b = np.concatenate((x,y),axis=1)
b

array([[ 3, 4, 14, 4],
 [ 3, 13, 23, 2]])